after_failure:
- echo "After failure message!"
after_script:
- echo "ProtoCI build was a:$BINSTAR_BUILD_RESULT" | tee artifact1.txt
after_success:
- echo "ProtoCI BUILD SUCCESS"

engine:
- python
script:
 - conda install -c psteinberg protoci
 - protoci-difference-build .
install_channels:
- defaults
- python
package: conda-recipes
platform:
 - linux-64

user: conda-team
quiet: True

# change
# another change

envvars:
 - AAAAAAAAA=1
 - BBBBBBBBB=2